const data = {
  products: [
    {
      brand: 'Nike',
      slug: 'nike-tshirt-black',
      name: "Nike Men's Essential T-Shirt - Black",
      description:
        'Classic black t-shirt made with soft and comfortable cotton fabric.',
      category: 'Men',
      type: 'Basic',
      color: 'Black',
      productImage:
        'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b03f819431834785ba3daf7801374fc3_9366/Icone_Berlin_City_Originals_T-Shirt_White_IP6542_21_model.jpg',
      images: [
        './images/nike_black_tshirt_1.jpg',
        './images/nike_black_tshirt_2.jpg',
        './images/nike_black_tshirt_3.jpg',
      ],
      sizes: ['S', 'M', 'L', 'XL'],
      price: 24.99,
      countInStock: 15,
      rating: 2.3,
      numReviews: 10,
    },
    {
      brand: 'Adidas',
      slug: 'adidas-tshirt-white',
      name: "Adidas Men's Graphic T-Shirt - White",
      description:
        'White t-shirt featuring a bold Adidas logo print on the front.',
      category: 'Men',
      type: 'Graphic',
      color: 'White',
      productImage:
        'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b03f819431834785ba3daf7801374fc3_9366/Icone_Berlin_City_Originals_T-Shirt_White_IP6542_21_model.jpg',
      images: [
        './images/adidas_white_tshirt_1.jpg',
        './images/adidas_white_tshirt_2.jpg',
        './images/adidas_white_tshirt_3.jpg',
      ],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      price: 29.99,
      countInStock: 20,
      rating: 4.7,
      numReviews: 8,
    },
    {
      brand: 'Puma',
      slug: 'puma-tshirt-blue',
      name: "Puma Men's Active T-Shirt - Blue",
      description:
        'Lightweight and breathable blue t-shirt perfect for workouts or casual wear.',
      category: 'Men',
      type: 'Active',
      color: 'Blue',
      productImage:
        'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b03f819431834785ba3daf7801374fc3_9366/Icone_Berlin_City_Originals_T-Shirt_White_IP6542_21_model.jpg',
      images: [
        './images/puma_blue_tshirt_1.jpg',
        './images/puma_blue_tshirt_2.jpg',
        './images/puma_blue_tshirt_3.jpg',
      ],
      sizes: ['S', 'M', 'L'],
      price: 19.99,
      countInStock: 12,
      rating: 4.6,
      numReviews: 15,
    },
    {
      brand: 'Under Armour',
      slug: 'under-armour-tshirt-grey',
      name: "Under Armour Men's Tech T-Shirt - Grey",
      description:
        'Performance-driven grey t-shirt with moisture-wicking and quick-drying properties.',
      category: 'Men',
      type: 'Performance',
      color: 'Grey',
      productImage:
        'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b03f819431834785ba3daf7801374fc3_9366/Icone_Berlin_City_Originals_T-Shirt_White_IP6542_21_model.jpg',
      images: [
        './images/under_armour_grey_tshirt_1.jpg',
        './images/under_armour_grey_tshirt_2.jpg',
        './images/under_armour_grey_tshirt_3.jpg',
      ],
      sizes: ['M', 'L', 'XL', 'XXL'],
      price: 34.99,
      countInStock: 18,
      rating: 4.9,
      numReviews: 20,
    },
    {
      brand: 'Hanes',
      slug: 'hanes-tshirt-green',
      name: "Hanes Men's ComfortSoft T-Shirt - Green",
      description:
        'Soft and comfortable green t-shirt made from preshrunk cotton for a reliable fit.',
      category: 'Men',
      type: 'Comfort',
      color: 'Green',
      productImage:
        'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b03f819431834785ba3daf7801374fc3_9366/Icone_Berlin_City_Originals_T-Shirt_White_IP6542_21_model.jpg',
      images: [
        './images/hanes_green_tshirt_1.jpg',
        './images/hanes_green_tshirt_2.jpg',
        './images/hanes_green_tshirt_3.jpg',
      ],
      sizes: ['S', 'M', 'L', 'XL'],
      price: 14.99,
      countInStock: 25,
      rating: 4.5,
      numReviews: 10,
    },
    {
      brand: 'Gildan',
      slug: 'gildan-tshirt-red',
      name: "Gildan Men's Heavy Cotton T-Shirt - Red",
      description:
        'Classic red t-shirt made from durable and heavyweight cotton fabric.',
      category: 'Men',
      type: 'Basic',
      color: 'Red',
      productImage:
        'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b03f819431834785ba3daf7801374fc3_9366/Icone_Berlin_City_Originals_T-Shirt_White_IP6542_21_model.jpg',
      images: [
        './images/gildan_red_tshirt_1.jpg',
        './images/gildan_red_tshirt_2.jpg',
        './images/gildan_red_tshirt_3.jpg',
      ],
      sizes: ['M', 'L', 'XL', 'XXL'],
      price: 17.99,
      countInStock: 30,
      rating: 4.7,
      numReviews: 12,
    },
    {
      brand: 'American Apparel',
      slug: 'american-apparel-tshirt-yellow',
      name: 'American Apparel Unisex Fine Jersey T-Shirt - Yellow',
      description:
        'Bright yellow unisex t-shirt made from fine jersey fabric for a soft and smooth feel.',
      category: 'Unisex',
      type: 'Fashion',
      color: 'Yellow',
      productImage:
        'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b03f819431834785ba3daf7801374fc3_9366/Icone_Berlin_City_Originals_T-Shirt_White_IP6542_21_model.jpg',
      images: [
        './images/american_apparel_yellow_tshirt_1.jpg',
        './images/american_apparel_yellow_tshirt_2.jpg',
        './images/american_apparel_yellow_tshirt_3.jpg',
      ],
      sizes: ['S', 'M', 'L'],
      price: 22.99,
      countInStock: 20,
      rating: 4.6,
      numReviews: 8,
    },
    {
      brand: 'Bella + Canvas',
      slug: 'bella-canvas-tshirt-pink',
      name: "Bella + Canvas Women's Relaxed T-Shirt - Pink",
      description:
        'Relaxed-fit pink t-shirt made from soft and lightweight fabric with a flattering drape.',
      category: 'Women',
      type: 'Casual',
      color: 'Pink',
      productImage:
        'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b03f819431834785ba3daf7801374fc3_9366/Icone_Berlin_City_Originals_T-Shirt_White_IP6542_21_model.jpg',
      images: [
        './images/bella_canvas_pink_tshirt_1.jpg',
        './images/bella_canvas_pink_tshirt_2.jpg',
        './images/bella_canvas_pink_tshirt_3.jpg',
      ],
      sizes: ['XS', 'S', 'M', 'L'],
      price: 19.99,
      countInStock: 15,
      rating: 4.8,
      numReviews: 10,
    },
    {
      brand: 'Fruit of the Loom',
      slug: 'fruit-of-the-loom-tshirt-white',
      name: "Fruit of the Loom Women's V-Neck T-Shirt - White",
      description:
        'Classic white v-neck t-shirt made from soft and breathable cotton fabric.',
      category: 'Women',
      type: 'Basic',
      color: 'White',
      productImage:
        'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b03f819431834785ba3daf7801374fc3_9366/Icone_Berlin_City_Originals_T-Shirt_White_IP6542_21_model.jpg',
      images: [
        './images/fruit_of_the_loom_white_tshirt_1.jpg',
        './images/fruit_of_the_loom_white_tshirt_2.jpg',
        './images/fruit_of_the_loom_white_tshirt_3.jpg',
      ],
      sizes: ['S', 'M', 'L', 'XL'],
      price: 16.99,
      countInStock: 18,
      rating: 4.7,
      numReviews: 12,
    },
    {
      brand: 'Champion',
      slug: 'champion-tshirt-blue',
      name: "Champion Women's Logo T-Shirt - Blue",
      description:
        'Blue t-shirt featuring a bold Champion logo print on the front.',
      category: 'Women',
      type: 'Graphic',
      color: 'Blue',
      productImage:
        'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b03f819431834785ba3daf7801374fc3_9366/Icone_Berlin_City_Originals_T-Shirt_White_IP6542_21_model.jpg',
      images: [
        './images/champion_blue_tshirt_1.jpg',
        './images/champion_blue_tshirt_2.jpg',
        './images/champion_blue_tshirt_3.jpg',
      ],
      sizes: ['XS', 'S', 'M', 'L'],
      price: 29.99,
      countInStock: 20,
      rating: 4.7,
      numReviews: 8,
    },
    {
      brand: 'Next Level',
      slug: 'next-level-tshirt-black',
      name: "Next Level Women's Triblend T-Shirt - Black",
      description:
        'Black triblend t-shirt made from a unique blend of cotton, polyester, and rayon for a soft and comfortable feel.',
      category: 'Women',
      type: 'Fashion',
      color: 'Black',
      productImage:
        'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b03f819431834785ba3daf7801374fc3_9366/Icone_Berlin_City_Originals_T-Shirt_White_IP6542_21_model.jpg',
      images: [
        './images/next_level_black_tshirt_1.jpg',
        './images/next_level_black_tshirt_2.jpg',
        './images/next_level_black_tshirt_3.jpg',
      ],
      sizes: ['S', 'M', 'L'],
      price: 21.99,
      countInStock: 12,
      rating: 4.6,
      numReviews: 15,
    },
    {
      brand: 'Bella + Canvas',
      slug: 'bella-canvas-tshirt-grey',
      name: "Bella + Canvas Men's Triblend T-Shirt - Grey",
      description:
        'Grey triblend t-shirt with a relaxed fit, made from a soft and lightweight blend of cotton, polyester, and rayon.',
      category: 'Men',
      type: 'Fashion',
      color: 'Grey',
      productImage:
        'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b03f819431834785ba3daf7801374fc3_9366/Icone_Berlin_City_Originals_T-Shirt_White_IP6542_21_model.jpg',
      images: [
        './images/bella_canvas_grey_tshirt_1.jpg',
        './images/bella_canvas_grey_tshirt_2.jpg',
        './images/bella_canvas_grey_tshirt_3.jpg',
      ],
      sizes: ['S', 'M', 'L', 'XL'],
      price: 23.99,
      countInStock: 18,
      rating: 4.8,
      numReviews: 10,
    },
    {
      brand: 'Gildan',
      slug: 'gildan-tshirt-yellow',
      name: "Gildan Men's Softstyle T-Shirt - Yellow",
      description:
        'Bright yellow t-shirt made from soft and comfortable cotton fabric.',
      category: 'Men',
      type: 'Basic',
      color: 'Yellow',
      productImage:
        'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b03f819431834785ba3daf7801374fc3_9366/Icone_Berlin_City_Originals_T-Shirt_White_IP6542_21_model.jpg',
      images: [
        './images/gildan_yellow_tshirt_1.jpg',
        './images/gildan_yellow_tshirt_2.jpg',
        './images/gildan_yellow_tshirt_3.jpg',
      ],
      sizes: ['M', 'L', 'XL', 'XXL'],
      price: 18.99,
      countInStock: 25,
      rating: 4.5,
      numReviews: 10,
    },
    {
      brand: 'Fruit of the Loom',
      slug: 'fruit-of-the-loom-tshirt-green',
      name: "Fruit of the Loom Women's Crewneck T-Shirt - Green",
      description:
        'Classic green crewneck t-shirt made from preshrunk cotton for a comfortable fit wash after wash.',
      category: 'Women',
      type: 'Basic',
      color: 'Green',
      productImage:
        'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b03f819431834785ba3daf7801374fc3_9366/Icone_Berlin_City_Originals_T-Shirt_White_IP6542_21_model.jpg',
      images: [
        './images/fruit_of_the_loom_green_tshirt_1.jpg',
        './images/fruit_of_the_loom_green_tshirt_2.jpg',
        './images/fruit_of_the_loom_green_tshirt_3.jpg',
      ],
      sizes: ['S', 'M', 'L', 'XL'],
      price: 15.99,
      countInStock: 30,
      rating: 4.9,
      numReviews: 20,
    },
    {
      brand: 'Champion',
      slug: 'champion-tshirt-red',
      name: "Champion Men's Heritage T-Shirt - Red",
      description:
        'Red t-shirt featuring the classic Champion logo embroidered on the chest.',
      category: 'Men',
      type: 'Graphic',
      color: 'Red',
      productImage:
        'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b03f819431834785ba3daf7801374fc3_9366/Icone_Berlin_City_Originals_T-Shirt_White_IP6542_21_model.jpg',
      images: [
        './images/champion_red_tshirt_1.jpg',
        './images/champion_red_tshirt_2.jpg',
        './images/champion_red_tshirt_3.jpg',
      ],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      price: 27.99,
      countInStock: 20,
      rating: 4.7,
      numReviews: 12,
    },
    {
      brand: 'Hanes',
      slug: 'hanes-tshirt-blue',
      name: "Hanes Women's Nano-T T-Shirt - Blue",
      description:
        "Light blue t-shirt made from Hanes' proprietary Nano-T fabric for a softer feel and lightweight fit.",
      category: 'Women',
      type: 'Comfort',
      color: 'Blue',
      productImage:
        'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b03f819431834785ba3daf7801374fc3_9366/Icone_Berlin_City_Originals_T-Shirt_White_IP6542_21_model.jpg',
      images: [
        './images/hanes_blue_tshirt_1.jpg',
        './images/hanes_blue_tshirt_2.jpg',
        './images/hanes_blue_tshirt_3.jpg',
      ],
      sizes: ['S', 'M', 'L', 'XL'],
      price: 13.99,
      countInStock: 18,
      rating: 4.7,
      numReviews: 12,
    },
    {
      brand: 'Under Armour',
      slug: 'under-armour-tshirt-black',
      name: "Under Armour Women's Tech Twist T-Shirt - Black",
      description:
        "Black t-shirt with a twist detail made from Under Armour's Tech fabric for superior moisture-wicking and breathability.",
      category: 'Women',
      type: 'Performance',
      color: 'Black',
      productImage:
        'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b03f819431834785ba3daf7801374fc3_9366/Icone_Berlin_City_Originals_T-Shirt_White_IP6542_21_model.jpg',
      images: [
        './images/under_armour_black_tshirt_1.jpg',
        './images/under_armour_black_tshirt_2.jpg',
        './images/under_armour_black_tshirt_3.jpg',
      ],
      sizes: ['M', 'L', 'XL'],
      price: 31.99,
      countInStock: 15,
      rating: 4.8,
      numReviews: 10,
    },
    {
      brand: 'Nike',
      slug: 'nike-tshirt-orange',
      name: "Nike Women's Dri-FIT T-Shirt - Orange",
      description:
        "Bright orange t-shirt made from Nike's Dri-FIT fabric for enhanced sweat-wicking performance during workouts.",
      category: 'Women',
      type: 'Active',
      color: 'Orange',
      productImage:
        'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b03f819431834785ba3daf7801374fc3_9366/Icone_Berlin_City_Originals_T-Shirt_White_IP6542_21_model.jpg',
      images: [
        './images/nike_orange_tshirt_1.jpg',
        './images/nike_orange_tshirt_2.jpg',
        './images/nike_orange_tshirt_3.jpg',
      ],
      sizes: ['S', 'M', 'L', 'XL'],
      price: 28.99,
      countInStock: 20,
      rating: 4.6,
      numReviews: 8,
    },
    {
      brand: 'Adidas',
      slug: 'adidas-tshirt-grey',
      name: "Adidas Women's Essentials T-Shirt - Grey",
      description:
        'Heather grey t-shirt featuring the Adidas logo on the chest for a sporty and casual look.',
      category: 'Women',
      type: 'Lifestyle',
      color: 'Grey',
      productImage:
        'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b03f819431834785ba3daf7801374fc3_9366/Icone_Berlin_City_Originals_T-Shirt_White_IP6542_21_model.jpg',
      images: [
        './images/adidas_grey_tshirt_1.jpg',
        './images/adidas_grey_tshirt_2.jpg',
        './images/adidas_grey_tshirt_3.jpg',
      ],
      sizes: ['XS', 'S', 'M', 'L'],
      price: 26.99,
      countInStock: 12,
      rating: 4.7,
      numReviews: 15,
    },
  ],
};

module.exports = data;
